# Generated by Django 4.2.6 on 2024-05-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, null=True)),
                ('audience_score', models.IntegerField(null=True)),
                ('critic_score', models.IntegerField(null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.profile')),
            ],
        ),
    ]
