# Generated by Django 4.2.6 on 2024-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_audience_score_alter_movie_critic_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_discovered_before',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
