# Generated by Django 4.2.6 on 2024-06-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_profile_has_discovered_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_discovered_before',
        ),
    ]
